import {chain,contract,explorer} from "./client";
import deployment from "./deployment.json";

const sections=[
  ["overview","What is VeriStep"],["genlayer","Why GenLayer"],["workflow","Workflow"],
  ["evidence","Evidence & immutable handoffs"],["judgment","Judgment states"],
  ["inconclusive","Inconclusive review & timeouts"],["settlement","Role-specific settlement"],
  ["deployment","Studio Next deployment"],["future","Future recovery extensions"],
] as const;

export function Docs(){
  return <article className="vs-docs" aria-labelledby="docs-title">
    <header><span className="eyebrow">VERISTEP / DOCUMENTATION</span><h1 id="docs-title">Accountability, explained.</h1><p>Immutable handoffs. Evidence-based judgment. Settlement for each agent’s exact duties.</p><a href="#workspace">Open workspace →</a></header>
    <div className="docs-layout"><nav aria-label="Documentation sections">{sections.map(([id,label])=><a key={id} href={`#docs?section=${id}`}>{label}</a>)}</nav><div className="docs-content">
      <section id="docs-overview"><h2>What is VeriStep</h2><p>A client freezes source terms. Agent A creates an immutable artifact; Agent B works from that finalized handoff. GenLayer validators assess the exact frozen duties, and the Intelligent Contract derives role-specific settlement.</p><p>The worker service produces and submits artifacts. It cannot decide responsibility, rewrite duties or choose settlement.</p></section>
      <section id="docs-genlayer"><h2>Why GenLayer</h2><p>A hash proves byte identity. An event log records an action. Deterministic execution applies rules. These alone do not determine semantic responsibility: did Agent A change a source rule? Did Agent B preserve the finalized upstream handoff? Which agent introduced a contradiction, and is each obligation satisfied by the complete evidence?</p><p>GenLayer’s leader and independent validators assess semantic obligations against the same committed artifacts. The contract validates the structured report and applies the frozen settlement consequences.</p></section>
      <section id="docs-workflow"><h2>Workflow</h2><ol className="docs-flow">{["Client freezes terms and funds fees","Agent A accepts, bonds and submits","Immutable A handoff becomes B’s input","Agent B accepts, bonds and submits","A participant requests review","GenLayer judgment assesses frozen duties","Contract allocates settlement; each transfer is routed explicitly"].map(step=><li key={step}>{step}</li>)}</ol></section>
      <section id="docs-evidence"><h2>Evidence &amp; immutable handoffs</h2><p>SOURCE, Agent A and Agent B artifacts bind a GitHub repository identity, immutable commit, path, blob, content type, exact byte length and whole-file SHA-256. Validators independently fetch and verify the complete committed UTF-8 artifacts before semantic review.</p><p>A’s submission references SOURCE’s submission ID; B references A’s finalized submission ID. The manifest freezes obligations, worker identities, fees, bonds, penalties and time windows. The current contract permits no artifact revisions: original handoffs and frozen duties cannot be silently rewritten.</p><p>Successful evidence acquisition is required to resolve a semantic review. A fetch or consensus failure does not itself prove an agent violation or create an authoritative report.</p></section>
      <section id="docs-judgment"><h2>Judgment states</h2><dl className="docs-definitions"><div><dt>SATISFIED</dt><dd>The assessment finds that the evidence supports the obligation being met.</dd></div><div><dt>VIOLATED</dt><dd>The assessment establishes an obligation was broken. A deterministic delivery failure can also establish a violation.</dd></div><div><dt>UNASSESSABLE</dt><dd>Available evidence does not support a determinate conclusion. <strong>UNASSESSABLE ≠ VIOLATED. Uncertainty alone is not agent fault.</strong></dd></div></dl><p>The contract derives each agent’s outcome from its relevant semantic and system checks: an established violation takes precedence; otherwise an unassessable check makes the role unassessable; otherwise the role is satisfied. An uncertain obligation does not erase a separate proven violation.</p><p>A displayed percentage measures semantic obligations satisfied, not AI confidence. An unassessable semantic obligation makes that role’s score unavailable; system checks still affect its final outcome.</p></section>
      <section id="docs-inconclusive"><h2>Inconclusive review &amp; timeouts</h2><p><code>INCONCLUSIVE</code> is a deal-level state. Outcomes and entitlements remain separate for A and B. It does not reset both agents to neutral.</p><h3>Path A — a report already exists</h3><p>When <code>resolve_review</code> produces a report with an unassessable role, its next state is <code>NEUTRAL_UNWIND_REQUIRED</code> and the deal becomes <code>INCONCLUSIVE</code>. The report preserves both roles’ outcomes and entitlements. No settlement legs are activated or routed during the remaining frozen adjudication window.</p><p>After the stored <code>adjudication_deadline</code>, a successful <code>advance_timeout</code> reuses that report. It changes the report’s next state to settlement-ready and creates legs from the existing entitlements. It does not turn a satisfied agent into an unassessable one.</p><h3>Path B — review has not resolved</h3><p>If the deal remains <code>REVIEW_REQUESTED</code> without a report at expiry, <code>advance_timeout</code> creates an <code>ADJUDICATION_TIMEOUT</code> report. Both roles are <code>UNASSESSABLE</code>, with neutral entitlements for each. There is no determinate semantic report to preserve.</p><h3>Delivery failure is different</h3><p>An A delivery timeout assigns A <code>VIOLATED</code> and B <code>UNASSESSABLE</code>. A B delivery timeout assigns A <code>UNASSESSABLE</code> and B <code>VIOLATED</code>. Missing the review-request window produces neutral outcomes for both. An acceptance timeout returns funded fees and only bonds actually deposited.</p><p>Deadlines do not execute transactions automatically. These transitions require a successful <code>advance_timeout</code> call.</p></section>
      <section id="docs-settlement"><h2>Role-specific settlement</h2><p>For a funded, bonded role, the contract applies the following frozen formulas. These are allocations, not evidence of payment.</p><div className="docs-table" tabIndex={0} role="region" aria-label="Entitlement formulas"><table><thead><tr><th>Role outcome</th><th>Agent fee</th><th>Client refund</th><th>Agent bond return</th></tr></thead><tbody><tr><th>SATISFIED</th><td>Full fee</td><td>0</td><td>Full bond</td></tr><tr><th>VIOLATED</th><td>0</td><td>Fee + frozen penalty</td><td>Bond − frozen penalty</td></tr><tr><th>UNASSESSABLE</th><td>0</td><td>Role’s fee</td><td>Full bond; no penalty</td></tr></tbody></table></div><p>Neutral unwind is role-specific. For example, A <code>SATISFIED</code> and B <code>UNASSESSABLE</code> preserves A’s fee and full bond, with no refund of A’s fee. B receives no fee and its full bond is returned; B’s fee goes back to the client without a violation penalty. The deal becoming inconclusive does not change these allocations.</p><h3>Allocation → dispatch → receipt status</h3><p><code>SETTLEMENT_PENDING</code> means settlement legs have been created. Nonzero allocations begin as <code>ELIGIBLE</code>; each still requires <code>route_settlement(deal_id, leg_id)</code>. The status alone does not mean money has moved.</p><p>After routing, the leg is <code>DISPATCHED_UNVERIFIED</code>: a native transfer is dispatched when its parent transaction finalizes. Studio Next provides no recipient-side receipt or callback that this contract can verify, so VeriStep does not label it paid or confirmed. The stored deal status remains <code>SETTLEMENT_PENDING</code> even when all legs are dispatched.</p></section>
      <section id="docs-deployment"><h2>Studio Next deployment</h2><dl className="docs-definitions"><div><dt>Network</dt><dd>{chain.name}</dd></div><div><dt>Chain ID</dt><dd>{chain.id}</dd></div><div><dt>Active contract</dt><dd><a href={`${explorer}/contracts/${contract}`} target="_blank" rel="noreferrer"><code>{contract}</code> ↗</a></dd></div><div><dt>Live DApp</dt><dd><a href="https://veristep-genlayer.vercel.app/" target="_blank" rel="noreferrer">veristep-genlayer.vercel.app ↗</a></dd></div></dl><details><summary>Technical details &amp; limitations</summary><p>The current release blocks timeout signing in the frontend because the no-broadcast simulation has not proven the required chain-time predicate. The timeout rules describe implemented contract behavior; this action is not currently enabled in the DApp.</p><p><a href={`${explorer}/transactions/${deployment.deploymentTransaction}`} target="_blank" rel="noreferrer">Inspect the deployment transaction ↗</a></p><p>Deployed source SHA-256: <code>{deployment.sourceHash}</code></p><ul>{deployment.limitations.map(item=><li key={item}>{item}</li>)}</ul><p><a href="https://github.com/tanphung/veristep/blob/main/docs/RELEASE-EVIDENCE.md" target="_blank" rel="noreferrer">Release evidence ↗</a></p></details></section>
      <section id="docs-future"><h2>Future Recovery Extensions</h2><p>Today, the current contract withholds settlement activation during the frozen adjudication window. If the deal remains inconclusive at expiry, a successful timeout transition preserves the existing role-specific outcomes and activates their recorded entitlements, including neutral unwind for unassessable roles, before settlement legs can be routed.</p><p>The recovery steps below would require a future contract version and are not part of the current Studio Next deployment.</p><p><strong>Planned improvements — not available in the current deployment.</strong> The current VeriStep contract remains unchanged. Future versions could extend the UNASSESSABLE → INCONCLUSIVE path without rewriting the original handoff or changing frozen obligations.</p><h3>1. Append-only evidence recovery</h3><p>When a report identifies specific <code>missing_evidence_ids</code>, an affected participant could append narrowly scoped supporting evidence. Original SOURCE, A and B artifacts, frozen obligations and handoff lineage would remain immutable. Supporting evidence would supplement the record, not replace it.</p><h3>2. One bounded GenLayer re-review</h3><p>A future contract could permit one additional review of the original artifacts, obligations, judgment and newly appended evidence. Participants could not rewrite the task or handoff. A single bounded round would prevent infinite review loops.</p><h3>3. Existing neutral unwind remains the fallback</h3><p>If the additional review still returns an unassessable role, or the recovery window expires, that role would use neutral-unwind entitlements while determinate role outcomes remain preserved. The design targets safety—uncertainty alone never becomes a violation—and liveness—a bounded path to settlement activation, followed by explicit routing.</p><h3>Proposed future flow</h3><ol className="docs-flow"><li>GenLayer review → UNASSESSABLE → INCONCLUSIVE</li><li>Settlement activation withheld</li><li>Append missing evidence</li><li>One bounded GenLayer re-review</li><li>Determinate result → role-specific settlement</li><li>Still unassessable / recovery expiry → role-specific neutral fallback</li></ol></section>
    </div></div>
  </article>;
}
