import {useRef,useState,type FormEvent} from "react";
import {ArrowLeft,ArrowRight,Check,FileKey2,Scale,Users} from "lucide-react";
import type {Address} from "genlayer-js/types";
import {githubCommitment,githubOrigin} from "./v2-evidence";
import {submitV2} from "./v2-transactions";
import {friendlyError} from "./errors";
import {rawAmount} from "./V2Actions";

const steps=[{title:"Participants",icon:Users},{title:"Evidence",icon:FileKey2},{title:"Obligations",icon:Check},{title:"Terms",icon:Scale}];
const evidenceCommit="5502b42323eb533306dbae2c82cf0e0f25b6cd8b";
const templates=[
  {id:"refund",label:"Refund policy",path:"templates/refund-policy.md",summary:"Refund windows, required proof and the consumed-service exception.",obligationA:"Stage A must preserve the refund window, required identifiers, non-refundable fees, and the final service-availability exception.",obligationB:"Stage B must faithfully report every refund condition from Stage A without turning eligibility into an approval guarantee."},
  {id:"export",label:"Export rights",path:"templates/export-rights.md",summary:"Trial restrictions, approval, excluded data and preservation holds.",obligationA:"Stage A must preserve account-tier restrictions, administrator approval, export scope, exclusions, and the final preservation-hold exception.",obligationB:"Stage B must faithfully report Stage A's export conditions without omitting or weakening the final preservation-hold exception."},
  {id:"eligibility",label:"Eligibility",path:"templates/eligibility.md",summary:"Age, region, identity evidence, deadline and non-guarantee language.",obligationA:"Stage A must preserve every eligibility requirement, the review-only meaning of eligibility, and the final late-submission exception.",obligationB:"Stage B must faithfully report Stage A without presenting eligibility as guaranteed approval or dropping the deadline exception."},
] as const;

export function V2NewDeal({account,onClose,onSubmitted}:{account?:Address;onClose:()=>void;onSubmitted:(id:string)=>void}){
  const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[templateId,setTemplateId]=useState<(typeof templates)[number]["id"]>("export");
  const template=templates.find(item=>item.id===templateId)??templates[1];
  const formRef=useRef<HTMLFormElement>(null);
  function move(next:number){const panel=formRef.current?.querySelector<HTMLElement>(`[data-step="${step}"]`);if(next>step&&panel){for(const field of panel.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>("input,textarea"))if(!field.reportValidity())return;}setError("");setStep(next);}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!account||busy||step!==steps.length-1)return;setBusy(true);setError("");try{
    const form=new FormData(event.currentTarget),value=(name:string)=>String(form.get(name)??"").trim();
    const dealId=value("dealId"),workerA=value("workerA"),workerB=value("workerB");
    if(!/^[a-z0-9][a-z0-9-]{0,63}$/.test(dealId))throw new Error("Deal ID must use lowercase letters, numbers and hyphens");
    if(!/^0x[\da-fA-F]{40}$/.test(workerA)||!/^0x[\da-fA-F]{40}$/.test(workerB)||new Set([account.toLowerCase(),workerA.toLowerCase(),workerB.toLowerCase()]).size!==3)throw new Error("Client and both workers must be distinct valid addresses");
    const source=await githubCommitment(value("sourceOwner"),value("sourceRepo"),value("sourceCommit"),value("sourcePath"));
    const originA=await githubOrigin(value("aOwner"),value("aRepo")),originB=await githubOrigin(value("bOwner"),value("bRepo"));
    const feeA=rawAmount(value("feeA")),feeB=rawAmount(value("feeB")),bondA=rawAmount(value("bondA")),bondB=rawAmount(value("bondB")),penaltyA=rawAmount(value("penaltyA")),penaltyB=rawAmount(value("penaltyB"));
    if(penaltyA>bondA||penaltyB>bondB)throw new Error("A penalty cannot exceed its worker bond");
    const terms={workers:{A:workerA,B:workerB},origins:{SOURCE:source.origin,A:originA,B:originB},source,money:{A:{fee:String(feeA),bond:String(bondA),penalty:String(penaltyA)},B:{fee:String(feeB),bond:String(bondB),penalty:String(penaltyB)}},windows:{accept:Number(value("acceptHours"))*3600,step:Number(value("stepHours"))*3600,review:Number(value("reviewHours"))*3600,adjudication:Number(value("adjudicationHours"))*3600},max_revisions:0,semantic_obligations:[{id:"SEM_A_SCOPE_ACCURACY",stage:"A",statement:value("obligationA"),evidence_ids:["SOURCE","A"]},{id:"SEM_B_FAITHFUL_HANDOFF",stage:"B",statement:value("obligationB"),evidence_ids:["A","B"]}]};
    for(const seconds of Object.values(terms.windows))if(!Number.isInteger(seconds)||seconds<60||seconds>30*86400)throw new Error("Every window must be between one minute and 30 days");
    await submitV2(account,dealId,"create_terms",[dealId,JSON.stringify(terms)]);onSubmitted(dealId);
  }catch(cause){setError(friendlyError(cause,"Could not create v2 deal"));}finally{setBusy(false);}}
  return <section className="new-job v2-new v2-wizard"><div className="section-heading"><div><span className="eyebrow">NEW V2 EVIDENCE DEAL</span><h2>Freeze every material promise first.</h2></div><button onClick={onClose}>Close</button></div><ol className="wizard-progress">{steps.map((item,index)=>{const Icon=item.icon;return <li className={index<step?"done":index===step?"current":""} key={item.title}><span>{index<step?<Check/>:<Icon/>}</span><strong>{item.title}</strong></li>;})}</ol>{error&&<p className="error">{error}</p>}<form ref={formRef} onSubmit={event=>void create(event)}><fieldset disabled={!account||busy}>
    <section data-step="0" hidden={step!==0}><span className="eyebrow">STEP 1 OF 4</span><h3>Who owns each signed action?</h3><p>Use three distinct wallets. Hosted A/B keys must match these worker addresses exactly.</p><div className="form-grid"><label>Deal ID<input name="dealId" required defaultValue={`evidence-${crypto.randomUUID().slice(0,8)}`} pattern="[a-z0-9][a-z0-9-]{0,63}"/></label><label>Worker A wallet<input name="workerA" required pattern="0x[0-9a-fA-F]{40}" placeholder="0x…"/></label><label>Worker B wallet<input name="workerB" required pattern="0x[0-9a-fA-F]{40}" placeholder="0x…"/></label></div></section>
    <section data-step="1" hidden={step!==1}><span className="eyebrow">STEP 2 OF 4</span><h3>Choose a reviewer-ready case and pin its complete source.</h3><p>The contract independently verifies repository identity, commit, path, blob, byte length and SHA-256.</p><div className="template-grid" role="radiogroup" aria-label="Evidence template">{templates.map(item=><button type="button" role="radio" aria-checked={item.id===templateId} className={item.id===templateId?"selected":""} onClick={()=>setTemplateId(item.id)} key={item.id}><strong>{item.label}</strong><span>{item.summary}</span></button>)}</div><div className="form-grid" key={template.id}><label>Source owner<input name="sourceOwner" required defaultValue="tanphung"/></label><label>Source repository<input name="sourceRepo" required defaultValue="veristep-evidence"/></label><label>Source commit<input name="sourceCommit" required pattern="[0-9a-fA-F]{40}" defaultValue={evidenceCommit}/></label><label>Source path<input name="sourcePath" required defaultValue={template.path}/></label><label>A GitHub owner<input name="aOwner" required defaultValue="tanphung"/></label><label>A evidence repository<input name="aRepo" required defaultValue="veristep-evidence"/></label><label>B GitHub owner<input name="bOwner" required defaultValue="tanphung"/></label><label>B evidence repository<input name="bRepo" required defaultValue="veristep-evidence"/></label></div></section>
    <section data-step="2" hidden={step!==2}><span className="eyebrow">STEP 3 OF 4</span><h3>Name the exact duties validators must assess.</h3><p>These IDs and statements become immutable obligations. Agent output cannot add, omit or replace them.</p><div key={template.id} className="obligation-fields"><label>Stage A · SEM_A_SCOPE_ACCURACY<textarea name="obligationA" required maxLength={900} defaultValue={template.obligationA}/></label><label>Stage B · SEM_B_FAITHFUL_HANDOFF<textarea name="obligationB" required maxLength={900} defaultValue={template.obligationB}/></label></div></section>
    <section data-step="3" hidden={step!==3}><span className="eyebrow">STEP 4 OF 4</span><h3>Lock economics, deadlines and failure policy.</h3><div className="form-grid compact">{(["A","B"] as const).flatMap(role=>(["fee","bond","penalty"] as const).map(kind=><label key={`${role}-${kind}`}>{role} {kind} (GEN)<input name={`${kind}${role}`} required inputMode="decimal" defaultValue={kind==="fee"?"0.01":kind==="bond"?"0.005":"0.003"}/></label>))}<label>Accept hours<input name="acceptHours" required type="number" min="1" max="720" defaultValue="24"/></label><label>Step hours<input name="stepHours" required type="number" min="1" max="720" defaultValue="24"/></label><label>Review hours<input name="reviewHours" required type="number" min="1" max="720" defaultValue="24"/></label><label>Adjudication hours<input name="adjudicationHours" required type="number" min="1" max="720" defaultValue="24"/></label></div><div className="freeze-note"><FileKey2/><p><strong>Revision zero only.</strong> Deadlines, neutral unwind, exact obligation IDs and settlement formulas cannot be changed after funding.</p></div><label className="check"><input type="checkbox" required/>I verified identities, immutable evidence, duties, deadlines and settlement amounts.</label></section>
    <div className="wizard-controls"><button type="button" onClick={()=>move(step-1)} disabled={step===0}><ArrowLeft/> Back</button><span>{step+1} / {steps.length}</span>{step<steps.length-1?<button className="primary" type="button" onClick={()=>move(step+1)}>Continue <ArrowRight/></button>:<button className="primary" type="submit">{busy?"Preparing transaction…":account?"Create frozen terms":"Connect client wallet first"}</button>}</div>
  </fieldset></form></section>;
}
