import {useCallback,useEffect,useState} from "react";
import {Bot,PauseCircle,Play,RefreshCw} from "lucide-react";
import {toHex} from "viem";
import type {Address} from "genlayer-js/types";
import {chain} from "./client";
import deployment from "./deployment.json";
import {injected} from "./transactions";
import type {V2Deal} from "./v2-types";

interface WorkerState {run_id:string;state:"ACTIVE"|"COMPLETE"|"ERROR"|"CANCELLED";stage:string;detail:string;updated_at:number}
interface WorkerHealth {ready:boolean;network:{chainId:number;contract:string;workers:{A:string;B:string}}}
const workerUrl=String(import.meta.env.VITE_VERISTEP_WORKER_URL??deployment.workerUrl??"").replace(/\/$/,"");

function authMessage(input:{address:string;nonce:string;expiresAt:number;chainId:number;contract:string;dealId:string;termsHash:string}){
  return ["VeriStep hosted worker authorization v1",`address:${input.address.toLowerCase()}`,`nonce:${input.nonce}`,`expires_at:${input.expiresAt}`,`chain_id:${input.chainId}`,`contract:${input.contract.toLowerCase()}`,`deal_id:${input.dealId}`,`terms_hash:${input.termsHash}`,"scope:start_or_resume_agent_ab"].join("\n");
}

export function V2Worker({deal,account}:{deal:V2Deal;account?:Address}){
  const key=`veristep:v2-worker:${chain.id}:${deal.contract.toLowerCase()}:${deal.deal_id}`;
  const [runId,setRunId]=useState(()=>localStorage.getItem(key)??""),[state,setState]=useState<WorkerState>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [health,setHealth]=useState<WorkerHealth>(),[healthError,setHealthError]=useState("");
  const client=account?.toLowerCase()===deal.manifest.client.toLowerCase();
  const eligible=["FUNDED","ACTIVE_A","ACTIVE_B"].includes(deal.status);
  const finalizedProof=Boolean(deal.deal_id==="v2-hosted-agent-live-2"&&deal.report&&["SETTLEMENT_PENDING","COMPLETED"].includes(deal.status));
  const healthMatchesDeal=Boolean(health&&health.network.chainId===chain.id&&health.network.contract.toLowerCase()===deal.contract.toLowerCase()&&health.network.workers.A.toLowerCase()===deal.manifest.terms.workers.A.toLowerCase()&&health.network.workers.B.toLowerCase()===deal.manifest.terms.workers.B.toLowerCase());
  const serviceReady=Boolean(health?.ready&&healthMatchesDeal);
  const loadHealth=useCallback(async()=>{if(!workerUrl)return;try{const response=await fetch(`${workerUrl}/api/health`,{cache:"no-store"}),data=await response.json() as WorkerHealth&{error?:string};if(!response.ok||typeof data.ready!=="boolean"||!data.network)throw new Error(data.error??"Hosted service health is unavailable");setHealth(data);setHealthError("");}catch(cause){setHealth(undefined);setHealthError(cause instanceof Error?cause.message:"Hosted service health is unavailable");}},[deal.deal_id]);
  const load=useCallback(async()=>{if(!workerUrl||!runId)return;try{const response=await fetch(`${workerUrl}/api/worker-runs/${encodeURIComponent(runId)}`,{cache:"no-store"}),data=await response.json() as {run?:WorkerState;error?:string};if(!response.ok||!data.run)throw new Error(data.error??"Hosted run unavailable");setState(data.run);setError("");}catch(cause){setError(cause instanceof Error?cause.message:"Hosted worker status unavailable");}},[runId]);
  useEffect(()=>{void loadHealth();},[loadHealth]);
  useEffect(()=>{void load();if(!runId)return;const timer=setInterval(()=>void load(),8000);return()=>clearInterval(timer);},[load,runId]);
  async function signedBody(){if(!account)throw new Error("Connect the client wallet first");const nonceResponse=await fetch(`${workerUrl}/api/worker-nonce?address=${account}`),nonce=await nonceResponse.json() as {nonce?:string;expiresAt?:number;error?:string};if(!nonceResponse.ok||!nonce.nonce||!nonce.expiresAt)throw new Error(nonce.error??"Could not create a worker authorization");const body={address:account,nonce:nonce.nonce,expiresAt:nonce.expiresAt,chainId:chain.id,contract:deal.contract,dealId:deal.deal_id,termsHash:deal.terms_hash};const signature=await injected().request({method:"personal_sign",params:[toHex(authMessage(body)),account]}) as string;return {...body,signature};}
  async function command(action:"start"|"resume"|"cancel"){setBusy(true);setError("");try{const body=await signedBody(),url=action==="start"?`${workerUrl}/api/worker-runs`:`${workerUrl}/api/worker-runs/${runId}/${action}`,response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),data=await response.json() as {runId?:string;run?:WorkerState;error?:string};if(!response.ok)throw new Error(data.error??"Hosted worker request failed");const id=data.runId??data.run?.run_id??runId;if(id){localStorage.setItem(key,id);setRunId(id);}await load();}catch(cause){setError(cause instanceof Error?cause.message:"Hosted worker request failed");}finally{setBusy(false);}}
  const serviceState=finalizedProof?"FINALIZED PROOF":state?.stage.replaceAll("_"," ")??(!workerUrl?"SERVICE UNAVAILABLE":healthError?"SERVICE UNAVAILABLE":!health?"CHECKING SERVICE":!health.ready?"SERVICE BLOCKED":!healthMatchesDeal?"CONFIGURATION MISMATCH":!eligible?"NOT ELIGIBLE":!client?"WALLET REQUIRED":"SERVICE READY");
  const detail=finalizedProof?"Finalized Agent A/B submissions and GenLayer adjudication are preserved in the Intelligent Contract.":state?.detail||(!workerUrl?"The hosted service URL is not configured.":healthError||(!health?"Checking the hosted service…":!health.ready?"The hosted service reports an unmet server-side dependency. Reviewer credentials are never required.":!healthMatchesDeal?"The hosted worker wallets do not match this deal's frozen participants.":!eligible?`This record is ${deal.status.replaceAll("_"," ")} and cannot start a new hosted delivery.`:!client?"Connect one client wallet to authorize this deal. VeriStep operates the separate Hosted Agent A and B wallets.":"One client-wallet signature authorizes this deal. VeriStep operates the separate Hosted Agent A and B wallets."));
  const currentHealth=!workerUrl||healthError?"Current worker health unavailable.":!health?"Checking current worker health…":health.ready&&healthMatchesDeal?"Current worker health: ready.":"Current worker health reports a configuration blocker.";
  return <section className={`v2-worker ${finalizedProof?"finalized-proof":""}`}><header><div className="worker-icon"><Bot/></div><div><span className="eyebrow">HOSTED AGENT HANDOFF</span><h2>Agent A extracts · Agent B reports</h2><p className="worker-description">Connect one client wallet. VeriStep's real backend agents use the dApp's server-side OpenAI API and separate Hosted Agent A/B wallets; each publishes immutable evidence and signs its own transaction, while B consumes A's finalized handoff.</p><p className="worker-boundary">GenLayer validators independently adjudicate the frozen obligations. The hosted worker does not decide responsibility or settlement.</p></div><span className={`worker-state ${finalizedProof?"complete":state?.state.toLowerCase()??(serviceReady?"ready":"locked")}`}>{serviceState}</span></header>{!finalizedProof&&error&&<p className="error">{error}</p>}<div className="worker-controls">{!finalizedProof&&!runId&&<button className="primary" disabled={!client||!eligible||busy||!serviceReady} onClick={()=>void command("start")}><Play/> Start A/B delivery</button>}{!finalizedProof&&runId&&<button onClick={()=>void load()} disabled={busy}><RefreshCw/> Refresh checkpoint</button>}{!finalizedProof&&state?.state==="ERROR"&&<button className="primary" onClick={()=>void command("resume")} disabled={!client||busy}><Play/> Resume safely</button>}{!finalizedProof&&state&&["ACTIVE","ERROR"].includes(state.state)&&<button onClick={()=>void command("cancel")} disabled={!client||busy}><PauseCircle/> Stop workflow</button>}<small>{detail}</small><small className="current-worker-health">{currentHealth}</small></div></section>;
}
